name: deploy_main

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: pull
    runs-on: ubuntu-22.04
    steps:
    - name: shh git pull and service restart
      uses: appleboy/ssh-action@v1.0.3
      env:
        MARVINETTE_DIR: ${{ vars.MARVINETTE_DIR }}
        MARVINETTE_BUILD_DIR : ${{ vars.MARVINETTE_BUILD_DIR }}

      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script_stop: true
        envs : MARVINETTE_DIR MARVINETTE_BUILD_DIR
        script: |
          cd $MARVINETTE_BUILD_DIR
          git fetch origin main
          git merge origin/main
          npm i
          rm -rf build/
          npm run build
          rm -rf $MARVINETTE_DIR/*
          cp -r server/ build/ node_modules/ $MARVINETTE_DIR
          # sudo /bin/systemctl restart marvinette